### ISSUE TITLE
Change Color

### ISSUE THREAD

**Issue by kevingamboa17** [martinheidegger/simple-terminal-menu#3]
Is there anyway to change the color menu?
thank you

**Comment by martinheidegger** [comment]
Thank you for asking: Yes, you just need to specify the `fg`/`bg` of the menu options that are passed to `terminal-menu`. I have updated the docs in respond to your question.

https://github.com/martinheidegger/simple-terminal-menu/commit/af6fe7951d139a7374bbed816180e349a7e48ae5

Since I think this answers your question I am closing this issue, please reopen if that doens't work for you.

**Comment by kevingamboa17** [comment]
Thanks!!! it works :)
but can i use rgb colors? i'm triying to, but it doesn't work.

thanks again for all.

**Comment by martinheidegger** [comment]
Terminal color definitions are problematic. Terminal menu uses charms for colors: https://www.npmjs.com/package/charm

**Comment by kevingamboa17** [comment]
Yeah, i get,  well, thank you so much!

you did a great work with simple terminal menu.
