### ISSUE TITLE
Color menu erro

### ISSUE THREAD

**Issue by Dam998** [martinheidegger/simple-terminal-menu#5]
Hi, why when I set orange as fg color menu the menu doesn't work?

thank you for your support

**Comment by martinheidegger** [comment]
Colors in the terminal are tricky, to reproduce your error it would be important to know what operating system and terminal software  you are using, how you specified the color and what exactly isn't working.

**Comment by Dam998** [comment]
I'm using:
- node 12.7
- windows pro
- cmd

my problem is that when I create settings for the menu and I set fg to orange my cmd crashes

this is my settings:

```
{
    width: 80,
    x: 1,
    y: 1,
    fg: 'orange',
    bg: 'black',
    padding: {
        left: 2,
        right: 2,
        top: 1,
        bottom: 1
    },
    selected: 0
}
```

**Comment by martinheidegger** [comment]
@Dam998 Sorry that I havn't been attentive to this issue. It would have helped quite a bit to have known the error that was thrown. It turned out that `orange` is a `chalk` web keyword that was not supported by `terminal-menu`. I updated `extended-terminal-menu` and now this package to version 2.0.0 which should allow orange to work. (it was a bit more work). You will find a few other things also fixed. cheers!

**Comment by Dam998** [comment]
Hi, thank you very much for your reply
I appreciate it

Have you updated your dependencies too? because when I create a bundle of my project with webpack I receive a worning that new Buffer() is deprecate, maybe 1 of your dependecies use it
Thank you @martinheidegger

**Comment by Dam998** [comment]
Test it right now
Thank you so much, now every things works perfect
Awesome work!

**Comment by martinheidegger** [comment]
@Dam998 This is indeed a dependency issue in https://github.com/substack/node-charm/blob/1f68b8a4cf3375f15dd01e2a0f7318ee37c58c75/lib/encode.js#L13 which probably should be fixed by someone.
